version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: "Asia/Jakarta"
    time: "00:00"
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    timezone: "Asia/Jakarta"
    time: "00:00"
  open-pull-requests-limit: 10
